spring:
    datasource:
        url: jdbc:mysql://localhost:3306/cherry
        username: root
        password: secret
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        database-platform: org.hibernate.dialect.MySQL5Dialect
        generate-ddl: true
        hibernate:
            ddl-auto: update

    liquibase:
        enabled: false
        drop-first: false
        change-log: classpath:db/changelog/db.changelog-master.xml